# Site
repository: RodneyPerhaps/RodneyPerhaps.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Jinsong Chen
title: Master Student 
email: jinsongchen4@gmail.com
website: https://rodneyperhaps.github.io/

# Dark Mode (true/false/never)
darkmode: true 

# Social links
#twitter_username: miehahahahahah
github_username:  RodneyPerhaps
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
linkedin_username: jinsongchen-iloveai
# xing_username: jekyll
# pinterest_username: jekyll
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/me_latest.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Jason Chen and I'm pursing the joint M.S. degree with the University of Chinese Academy of Sciences, and the  Institute of Computing Technology (ICT), Chinese Academy of Sciences under the supervision of Prof. Hu Han in 2021 and Prof. Xiao Jun in 2022.
  I also collaborated with Prof. Shiguang Shan closely.

  My research interests include <mark>3D computer vision</mark> and <mark>video algorithm</mark>.

  Before that, I obtained my bachelor degree from the Department of Information Security, Northwestern Polytechnical University (NWPU).

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Towards High-Fidelity Face Self-occlusion Recovery Via Multi-view Residual-based GAN Inversion, Chen Jinsong, Han Hu, and Shan Shiguang 
        link: https://ojs.aaai.org/index.php/AAAI/article/view/19905
        # link_text: Project Websit
        additional_links:
          - title:  RodneyPerhaps/MvInvert
            icon: fab fa-github
            url: github.com/RodneyPerhaps/MvInvert
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Thirty-Sixth AAAI Conference on Artificial Intelligence (AAAI 2022)
        description: | # this will include new lines to allow paragraphs
          - Approached the problem of natural face self-occlusion recovery using a new generative adversarial network.
          - Designed a multi-view Residual-based GAN Inversion to re-render and refine multi-view 2D images.
          - Designed a differentiable screened Poisson blending equation solving method.
          - Performed unsupervised training using unpaired data.
          - Got accepted by AAAI 2022 (with 4 accepts among 6 review comments).
          ![alt text](images/network_arch.png "Network Architecture")

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Apple R&D (Beijing) Limited Haidian Branch
        link: apple.com
        # link_text: boringcompany.com
        sub_title: Video Engineer Intern
        caption: May 2022 - Present
        quote: >
          Improve temporal consistency of different DL algorithms on videos
        description: | # this will include new lines to allow paragraphs
            - Assist teams to improve the temporal consistency of facial landmark detection on videos.
            - Investigate on how to improve temporal consistency of face relighting on videos.

      - layout: left
        title: Beijing Kuaishou Technology Co. Ltd.
        link: kuaishou.com
        # link_text: boringcompany.com
        sub_title: Facial Computer Vision Algorithm Intern
        caption: Nov. 2021 - May 2022 

        description: | # this will include new lines to allow paragraphs
            - Incorporated temporal consistency of 3D Morphable Model to eliminate predicted landmark jitter on videos.
            - Made notable improvements on stability under extreme poses.
            - Maintained accuracy comparable to SOTA methods and applied for a patent.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Chinese Academy of Sciences (UCAS)
      
        caption: 2020 - Present
        sub_title: M.S Computer Science
        description: | # this will include new lines to allow paragraphs
          - GPA: 3.45 / 4.0

      - layout: left
        title: Northwestern Polytechnical University (NWPU)
      
        caption: 2016 - 2020
        sub_title: BSc Information Security
        description: | # this will include new lines to allow paragraphs
          - GPA: 74 / 100


  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      MBTI character: 
      - ESTJ: The Director (Extraverted, Sensing, Thinking, Judging)
      
      Alongside my interests in DL/ML, some of my other interests and hobbies are:
      - Working out
      - Boxing
      - Gaming
      - Cooking 


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
